version: '3.3'
services:
  backend:
    container_name: backend
    build: .
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
    ports:
      - '3030:3030'
    command: ['sh', '-c', 'npm rebuild && npm install && npm run dev']
